```
1. Wczytanie zestawu danych punktowych oraz nadanie im ukladu wspolrzednych ETRS 1989 Poland CS2000 Zone 7 - EPSG:2178, nastepnie zapisanie ich do nowego pliku csv - zestaw1_epsg_2178.csv.
```

```{r}
library(sp)

data_points <- read.csv('zestaw1.csv', colClasses = c('numeric', 'numeric'))
head(data_points)
dim(data_points)

coord <- SpatialPoints(cbind(data_points$Long, data_points$Lat), 
                       proj4string = CRS('+proj=longlat'))
class(coord)
length(coord)
head(coord)

coordUTM <- spTransform(coord, CRS('+init=epsg:2178'))
head(coordUTM)
length(coordUTM)
#uklad CRS pomyslnie zmieniony z WGS84 na EPSG:2178

coordUTM_df <- as.data.frame(coordUTM) #col.names nie dziala - zbadac, z jakiego powodu
colnames(coordUTM_df) <- c('Lon', 'Lat')
head(coordUTM_df)
dim(coordUTM_df) #dlugosc zgadza sie z dlugoscia wczytanych danych

write.csv(coordUTM_df, "zestaw1_epsg_2178.csv", row.names = FALSE)
```

```
2. Wczytanie danych w ukladzie wspolrzednych EPSG:2178 oraz pliku shapefile zawierajacego osiedla.
```

```{r}
library(tidyverse)
library(ggplot2)
library(raster)

data <- read.csv('zestaw1_epsg_2178.csv')
head(data)
dim(data)

str(data) #2 zmienne - Lon oraz Lat numerical
sum(is.na(data)) #brak pustych danych

qplot(data$Lon, geom='histogram')

districts <- shapefile('osiedla.shp')
str(districts)
```

```
Wczytane dane maja rozmiar 2000 x 2, zaiweraja dlugosc i szerokosc geograficzna - typ numerical, zapisane sa w data.frame o nazwie data, brak pustych danych.
```

```
3. Prezentacja mapy dzielnic/osiedl w Krakowie z nalozonymi na nia wczytanymi punktami.
```

```{r}
map_with_points <- ggplot() + geom_point(data = data, aes(x = data$Lon, y = data$Lat ))
map_with_points + geom_polygon(data = districts, aes(x = long, y = lat, fill = id), show.legend = FALSE) + coord_fixed() 


```
```
4. Wydzielenie klastrow o zwiekszonej intensywnosci wystepowania wykroczen przy uzyciu algorytmow grupowania gestosciowego DBSCAN/ HBDSCAN / OPTICS.
```

```
4a
• DBSCAN (density-based spatial clustering of applications with noise)
```

```{r}
library(dbscan)

dbscan_clusters1 <- dbscan(data, minPts = 5, eps = 10)
dbscan_clusters1
map_with_points + geom_point(data = data, aes(x = Lon, y = Lat, color = dbscan_clusters1$cluster))

dbscan_clusters2 <- dbscan(data, minPts = 10, eps = 50)
map_with_points + geom_point(data = data, aes(x = Lon, y = Lat, color = dbscan_clusters2$cluster))

dbscan_clusters3 <- dbscan(data, minPts = 10, eps = 100)
map_with_points + geom_point(data = data, aes(x = Lon, y = Lat, color = dbscan_clusters3$cluster))

dbscan_clusters4 <- dbscan(data, minPts = 10, eps = 200)
map_with_points + geom_point(data = data, aes(x = Lon, y = Lat, color =dbscan_clusters4$cluster))

```

```
4b.
• OPTICS (ordering points to identify the clustering structure)
```

```
• DBSCAN (density-based spatial clustering of applications with noise)
• OPTICS (ordering points to identify the clustering structure)
• HDBSCAN (hierarchical DBSCAN)
```



